### ISSUE TITLE
Should `CLI` enforce a return, as `core` does?

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#151]
In `core`, you can't have your last operation _not_ return anything. So the following expression would produce a failure:
```js
fn(state => {
  console.log("not gonna return anything");
})
```
The logs look like this:
```
╭─────────────────────────────────────────────╮
│ ◲ ◱  @openfn/core#v1.4.8 (Node.js v18.10.0) │
│ ◳ ◰             @openfn/language-http@4.2.3 │
╰─────────────────────────────────────────────╯
no return
Error: Could not write state to file, type must be serializable. Got 'undefined'
    at /home/app/assets/node_modules/@openfn/core/lib/cli/execute-command.js:79:23
```
In `CLI`, the same expression succeeds and the logs look like this:
```
[CLI] ✔ Installing packages...
[CLI] ✔ Installation complete in 1.797s
[CLI] ✔ Loaded state from ./state.json
[CLI] ✔ Compiled job from helloWorld.js
[JOB] ℹ not gonna return anything
[R/T] ✔ Operation 1 complete in 0ms
[CLI] ✔ Writing output to ./output.json
[CLI] ✔ Done in 1.975s! ✨
```
Should they behave the same way? @josephjclark , @stuartc , curious to hear your thoughts on this one.

**Comment by josephjclark** [comment]
I don't think we should enforce anything. The new runtime will do a bit more management of state and so it can be a bit less dogmatic about this.

For context, here's my vision of state in the new runtime:

* There is no global state (so if you don't do `fn(state => { ... })` you get an error)
* A mutable state object is passed into each operation
* If a state object is returned, the returned object (whatever it is) will feed into the next operation 
* The state object is cloned before being passed into the next operation, so that any changes made by that operation are preserved

In this world, I don't think it matters if the state is actually returned by the operation. You can do, and it's probably a good convention.

Jobs which run on core would continue to run on the new runtime with this more generous rule, so back-compatibility wouldn't be a problem.

**Comment by stuartc** [comment]
I'm in agreement with @josephjclark, I like the opportunities that approach offers us. If we find that users keep stumbling on this we can address it in multiple ways such as warnings with compiler linting or warning in the log etc. 

I guess my point is, lets address the pending problem with warnings rather than making rules low down in the design - for now.
