### ISSUE TITLE
RTM Server: generate JWT for each attempt (Attempt Token)

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#370]
When we pull an attempt id from the queue, Lightning will give us a JWT for that attempt.

All subsequent requests for that Attempt MUST include this Attempt Token (as well as the Worker token)

Should we include the process id or some unique hash, to stop someone hijacking the token from a different thread? Maybe when acknowlegding the JWT from Lighting? ip address?

It would be useful from an admin perspective to be able to backtrace which server instance/process is associated with the token

The precise API for this needs settling on...

**Comment by josephjclark** [comment]
The JWT needs to expire after the timeout duration for the attempt

**Comment by stuartc** [comment]
@josephjclark heres an example using the `jose` module to create a HS256 (shared secret) jwt:

```js
const jwt = await new SignJWT(context.payload)
   .setProtectedHeader({ alg: 'HS256' })
   .sign(context.secret)
```

There does appear to be some functions in the library for "compact" encoding, which I think is preferable to reduce the size of the payload, culling spaces etc.

For decoding tokens there is: `decodeJwt(token)`, which doesn't verify.
And then `jwtVerify` for decoding and verifying [here](https://github.com/panva/jose/blob/main/docs/functions/jwt_verify.jwtVerify.md), I think we will start without verification for now because we should be able to trust our internal network - and I haven't thought much about the best way to distribute/communicate the public key that Lightning will use... If we get the token via an HTTPS connection thats good enough for me for now.

**Comment by josephjclark** [comment]
@stuartc are you sure we don't want to verify, for the Worker Token at least? Wasn't the whole point that we'd have a shared secret used by Lightning and the worker server?

**Comment by josephjclark** [comment]
Ok so talking to @stuartc, I think we're going to dive right in and use websockets for each attempt.

Each attempt will register a socket between Lightning and the Worker. This allows much quicker messaging during runs (which will be high throughput), reducing https handshakes and JWT parsing overheads.

We do need to work out a robust queue on the worker side for if the connection is dropped - messages need to be cached until the socket is restored. But we needed to do that anyway,

When creating the socket, we still need to use the Attempt token as auth.

So the flow will be something like this:

* Worker posts to `attempts/next` with the Worker token
* Lightning responds with an attempt id and an attempt JWT
* (Worker does not verify this JWT)
* Worker requests a websocket using the attempt JWT
* All events - start, end, log, etc are piped through the socket, which is robust to failure
* After the complete message is acknowledged, the attempt is done and the socket closed
