### ISSUE TITLE
Object to primitive value error

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#616]
When using salesforce's `bulk()` function via the CLI, we see a log (from [here](https://github.com/OpenFn/adaptors/blob/main/packages/salesforce/src/Adaptor.js#L371)) that looks like this:
```
[Object: null prototype] {
  '$': [Object: null prototype] {
    xmlns: 'http://www.force.com/2009/06/asyncapi/dataload'
  },
  id: '751S9000002POfeIAG',
  jobId: '750S9000002C6tKIAS',
  state: 'Queued',
  createdDate: '2024-02-29T11:51:14.000Z',
  systemModstamp: '2024-02-29T11:51:14.000Z',
  numberRecordsProcessed: '0',
  numberRecordsFailed: '0',
  totalProcessingTime: '0',
  apiActiveProcessingTime: '0',
  apexProcessingTime: '0'
}
```
And when we use that same job code on app.openfn.org (via the ws-worker, logger, etc.) we see a crash with this message:
```
Run complete with status: crash
ExecutionError: Cannot convert object to primitive value
```
I wonder if, somehow, the logger or the runtime or the ws-worker is trying to convert [this log](https://github.com/OpenFn/adaptors/blob/main/packages/salesforce/src/Adaptor.js#L371) to a string via `Object.toString()` but is unable because the "null prototype" object does not inherit the `toString` property.

cc @aleksa-krolls , @mtuchi , @josephjclark

**Comment by josephjclark** [comment]
Yeah we've got a raft of problems serialising error objects, it's something I've been struggling with for a while. I find it hard to repro cases and error objects in Javascript are basically rubbish.

The basic problem I think is that the logger interferes with and sometimes tries to serialise error objects.

There's a couple of related examples in #612 #582

**Comment by taylordowns2000** [comment]
@stuartc , @josephjclark - are you guys aware of any workarounds or temporary fixes for this? The WaterAid is blocked until we find a way forward with the crash that happens after using `bulk()` (top of this issue) and I'm wondering if a change to the adaptor might allow us to side-step this deeper issue and move forward.

**Comment by josephjclark** [comment]
I've just looked a bit closer and I see that it's not actually an error object. It's just an object being logged.

So my guess is that the worker is failing to serialize that object properly to send it out of the worker thread.

Options:
1. Remove that log line from the adaptor
1. Patch in some magic to the logger to serialize objects better (I have no idea what this means and it'll likely cause side effects)
1. Patch in a fix to the worker so that whatever this object is gets serialised properly.

I think the first step is to repro this on my local machine, then I can try to work out what's up with the actual error object.

**Comment by taylordowns2000** [comment]
Yeah it's the object.toString being called on some sort of special "null property" object. Google tells me this is a way of making an object that's just a map... no special JS object properties (like toString).

What if I stringify inside the adaptor for now? So the logger just logs a string?
