### ISSUE TITLE
Tailwind: what's the correct way to use styles in library components?

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#84]
The components we create in `kit` use embedded CSS to style themselves.

This causes problems in Lightning because tailwind utilities are defined several  times in conflicting CSS, resulting in weird stuff.

I have suggested a quick workaround that keeps us moving forward, but this needs more thought.

Seems to be that if I have a tailwind component with a bunch of util classes, it should "inherit" those classes from the parent app. So if I use `text-s` as 56px in my parent app, the component should use the same. Because of how Tailwind works, this approach (if its even correct) requires the parent app build to process the utility classes used by the components in node_modules.

I suspect the answer may be to create a Tailwind plugin for the component. I think this allows us to declare and contribute styles used by the library component to the parenting app, so it can generate the correct CSS. But this needs more research.

This problem has actually been on my mind all week, although until now it had felt a bit academic. I haven't been able to Google a good solution yet, but I will keep looking. The Tailwind UI library probably hold the answers (which is what clued me into plugins)

**Comment by stuartc** [comment]
I've just made a change to `adaptor-docs`, doing what your initial hunch is - produce an `index.css` file that the consumer decides how and when to import.

So in the case of Lightning since we also use tailwind we _don't_ import it - we point our tailwind config to go and sniff around the module to determine what styles should be added to it's css.

It is curious that this isn't an issue with `workflow-diagram` since it's the exact same initial setup. I can see it judiciously injecting CSS into the page - so I think we should take the same approach with that package as well.
